[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
python = "^3.7"
python-telegram-bot = "*"
telegram = "*"
yarl = "^1.4"
aiohttp = "^3.6"
telethon = "^1.10"
flask = "^1.1"
